In [1]:
import numpy as np
import tensorflow as tf
import pandas as pd

In [2]:
df = pd.read_csv("train.csv")
X = df.iloc[:,1:]
y = df.iloc[:,0]

In [3]:
X = X / 255
#There are 10 unique digits

In [4]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=5)

In [5]:
ann = tf.keras.models.Sequential()

#Adding Layers
ann.add(tf.keras.layers.Dense(units = 784,
                              activation = 'relu'))
ann.add(tf.keras.layers.Dense(units = 1300,
                              activation = 'relu'))
ann.add(tf.keras.layers.Dense(units = 1300,
                              activation = 'relu'))
#Sigmoid as it is a binary classification, it gives a probability of each class
ann.add(tf.keras.layers.Dense(units = 10,
                              activation = 'softmax'))

In [6]:
ann.compile(optimizer = 'adam',
            loss = 'sparse_categorical_crossentropy',
            metrics = ['accuracy'])

In [7]:
ann.fit(X_train, y_train, epochs = 40)

Epoch 1/40
1050/1050 [==============================] - 11s 10ms/step - loss: 0.2446 - accuracy: 0.9238
Epoch 2/40
1050/1050 [==============================] - 11s 10ms/step - loss: 0.1207 - accuracy: 0.9645
Epoch 3/40
1050/1050 [==============================] - 11s 10ms/step - loss: 0.0827 - accuracy: 0.9754
Epoch 4/40
1050/1050 [==============================] - 10s 10ms/step - loss: 0.0652 - accuracy: 0.9805
Epoch 5/40
1050/1050 [==============================] - 10s 10ms/step - loss: 0.0575 - accuracy: 0.9830
Epoch 6/40
1050/1050 [==============================] - 10s 10ms/step - loss: 0.0486 - accuracy: 0.9859
Epoch 7/40
1050/1050 [==============================] - 11s 10ms/step - loss: 0.0427 - accuracy: 0.9876
Epoch 8/40
1050/1050 [==============================] - 10s 10ms/step - loss: 0.0351 - accuracy: 0.9903
Epoch 9/40
1050/1050 [==============================] - 10s 10ms/step - loss: 0.0313 - accuracy: 0.9908
Epoch 10/40
1050/1050 [==============================] - 11s 10m

In [8]:
predictions = ann.predict(X_test)
predictions

array([[1.5804687e-11, 1.2207843e-05, 3.7240960e-05, ..., 2.2566371e-06,
        1.5905857e-04, 9.2230421e-06],
       [0.0000000e+00, 0.0000000e+00, 0.0000000e+00, ..., 0.0000000e+00,
        0.0000000e+00, 2.7033000e-36],
       [0.0000000e+00, 1.0000000e+00, 2.3158820e-37, ..., 0.0000000e+00,
        1.9157444e-34, 0.0000000e+00],
       ...,
       [0.0000000e+00, 1.0048950e-37, 0.0000000e+00, ..., 0.0000000e+00,
        1.0000000e+00, 0.0000000e+00],
       [0.0000000e+00, 0.0000000e+00, 0.0000000e+00, ..., 4.1644697e-32,
        1.8089177e-28, 3.3786823e-33],
       [1.0000000e+00, 0.0000000e+00, 0.0000000e+00, ..., 0.0000000e+00,
        0.0000000e+00, 0.0000000e+00]], dtype=float32)

In [39]:
from numpy import argmax
def get_digits(predictions):
    digits = []
    for i in range(0,len(predictions)):
        digits.append(argmax(predictions[i]))
    digits = np.array(digits)
    return digits

In [33]:
from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix
print(accuracy_score(digits, y_test))
print(confusion_matrix(digits, y_test))

0.9764285714285714
[[794   0   2   1   0   1   5   0   1   4]
 [  0 931   1   1   0   1   0   1   3   0]
 [  1   0 796   3   1   1   1   1   5   0]
 [  0   2   6 870   0   9   0   0   4   5]
 [  0   2   3   0 785   0   2   3   0   6]
 [  1   0   1   7   2 731   7   0   8   3]
 [  7   0   1   0   1   1 800   0   4   1]
 [  1   0   7   6   0   0   0 884   2   1]
 [  2   1   6   4   4   3   1   1 743   2]
 [  0   1   1   6   9   4   0  13   3 868]]


In [42]:
submission = pd.read_csv("test.csv")
submission_predictions = ann.predict(submission)
submisson_digits = get_digits(submission_predictions)

In [51]:
submission_df = pd.DataFrame(submisson_digits, columns=['Label'])
submission_df.to_csv('submission.csv')

In [59]:
submission_df

Label
0          2
1          0
2          9
3          9
4          3
...      ...
27995      9
27996      7
27997      3
27998      9
27999      2

[28000 rows x 1 columns]